import {useEffect,useMemo,useRef,useState} from 'react';
import SpaceStage from './SpaceStage.jsx';
import {event,ticker,about,venue,stages,program,privateZones,services,serviceSteps,participants,organizer,conferences,tariffFeatures,tariffs,links} from './content/site.js';
import {legacyContent} from './content/legacy.js';
import './style.css';

const gallerySources=Array.from({length:20},(_,i)=>`/assets/images/gallery/${String(i+1).padStart(2,'0')}.${i<9?'webp':'jpg'}`);
const stageImages=['/assets/images/venue/event.webp','/assets/images/venue/hall.webp','/assets/images/venue/lounge.webp'];
const localConference={
 'kazan-2026':'/assets/images/other-conferences/dolg-talk-kazan-2026.png',
 'dolg-2026':'/assets/images/other-conferences/dolg-talk-2026.png',
 'siberia-2026':'/assets/images/other-conferences/dolg-talk-siberia-2026.jpg',
 'debt-2025':'/assets/images/other-conferences/debt-tech-2025.jpg',
 'dolg-2025':'/assets/images/other-conferences/dolg-talk-2025.png',
 'kazan-2025':'/assets/images/other-conferences/dolg-talk-kazan-2025.png',
 'debt-2024':'/assets/images/other-conferences/debt-tech-2024.png',
 'analytics-2023':'/assets/images/other-conferences/analytics-finance-2023.png',
 'analytics-2022':'/assets/images/other-conferences/analytics-finance-2022.png',
 'petersburg-2021':'/assets/images/other-conferences/petersburg-collectors-2021.png'
};
const chapters=[
 ['00','Старт','top'],['01','О форуме','about'],['02','Место','venue'],['03','Кадры 2025','gallery'],['04','Программа','program'],['05','Сервисы','services'],['06','Участники','participants'],['07','Организатор','organizer'],['08','Архив','conferences'],['09','Тарифы','tariffs'],['10','Контакты','contacts']
];

function Arrow(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 19 19 5M8 5h11v11"/></svg>}
function Kicker({n,children}){return <div className="kicker"><span>{n}</span><b>{children}</b></div>}
function Action({children,onClick,href,ghost=false}){const C=href?'a':'button';return <C className={'action '+(ghost?'ghost':'')} onClick={onClick} href={href} target={href?.startsWith('http')?'_blank':undefined} rel="noreferrer"><span>{children}</span><Arrow/></C>}

function Countdown(){const [now,setNow]=useState(Date.now());useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);const diff=Math.max(0,new Date(event.target).getTime()-now);const cells=[[Math.floor(diff/864e5),'дней'],[Math.floor(diff/36e5)%24,'часов'],[Math.floor(diff/6e4)%60,'минут'],[Math.floor(diff/1e3)%60,'секунд']];return <div className="countdown">{cells.map(([v,l])=><div key={l}><strong>{String(v).padStart(2,'0')}</strong><small>{l}</small></div>)}</div>}

function ChapterNav({open,setOpen}){return <>
  <header className="topbar"><a href="#top" className="brand"><img src="/assets/debttech-logo.svg" alt="DEBT TECH 2026"/></a><div className="top-meta"><span>{event.date}</span><span>{event.city}</span></div><button className="menu-toggle" onClick={()=>setOpen(v=>!v)} aria-label="Открыть навигацию"><i/><i/></button></header>
  <nav className={'chapter-nav '+(open?'open':'')} aria-label="Навигация по сайту"><div className="chapter-nav-inner">{chapters.map(([n,label,id])=><a href={'#'+id} key={id} onClick={()=>setOpen(false)}><span>{n}</span><b>{label}</b></a>)}</div><div className="nav-bottom"><Action href="#tariffs">Ранняя регистрация</Action><a href="mailto:redchief@rvzrus.ru">redchief@rvzrus.ru</a></div></nav>
  <div className="progress" aria-hidden="true"><span/></div>
</>}

function Modal({kind,close,tariff}){const isStand=kind==='stand';const title=isStand?'Забронировать стенд':'Ранняя регистрация';const [sent,setSent]=useState(false);function submit(e){e.preventDefault();const fd=new FormData(e.currentTarget);const subject=encodeURIComponent(`DEBT TECH 2026 — ${title}${tariff?` / ${tariff.title}`:''}`);const body=encodeURIComponent([...fd.entries()].map(([k,v])=>`${k}: ${v}`).join('\n'));window.location.href=`mailto:redchief@rvzrus.ru?subject=${subject}&body=${body}`;setSent(true)}return <div className="modal" onMouseDown={e=>e.target===e.currentTarget&&close()}><section><button className="modal-close" onClick={close}>×</button><Kicker n="FORM">DEBT TECH / 2026</Kicker><h2>{title}</h2>{tariff&&<p className="modal-tariff">{tariff.title} · {tariff.price}</p>}{sent?<div className="modal-note">Почтовое приложение открыто. Если оно не запустилось, напишите на <a href="mailto:redchief@rvzrus.ru">redchief@rvzrus.ru</a>.</div>:<form onSubmit={submit}><label>ФИО<input name="ФИО" required/></label><label>Компания<input name="Компания" required/></label><label>Телефон<input name="Телефон" type="tel" required/></label><label>Email<input name="Email" type="email" required/></label>{isStand&&<label className="wide">Комментарий<textarea name="Комментарий" rows="3"/></label>}<button className="action wide" type="submit"><span>Продолжить</span><Arrow/></button></form>}</section></div>}

function DragRail({children,className=''}){const ref=useRef(null),drag=useRef(null);return <div ref={ref} className={'drag-rail '+className} onPointerDown={e=>{if(e.button!==0)return;drag.current={x:e.clientX,left:ref.current.scrollLeft};ref.current.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!drag.current)return;ref.current.scrollLeft=drag.current.left-(e.clientX-drag.current.x)}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>{children}</div>}

function Hero({openRegistration,openStand}){return <section className="scene hero" data-scene id="top"><div className="hero-shade"/><div className="hero-copy reveal"><Kicker n="00">ЕЖЕГОДНАЯ ФОРУМ-ВЫСТАВКА</Kicker><h1><span>DEBT</span><span>TECH</span><em>2026</em></h1><p>{event.headline}</p><div className="hero-actions"><Action onClick={openRegistration}>Ранняя регистрация</Action><Action ghost onClick={openStand}>Забронировать стенд</Action></div></div><div className="hero-orbit-note"><span>13 NOV 2026</span><b>55.75° N / 37.61° E</b></div><div className="hero-count"><small>{event.countdownLabel}</small><Countdown/></div><div className="ticker">{ticker.map((t,i)=><span key={i}>{t}</span>)}</div><a href="#about" className="scroll-cue"><i/>SCROLL TO DISCOVER</a></section>}

function About(){return <section className="scene editorial" data-scene id="about"><div className="editorial-grid reveal"><Kicker n="01">О ФОРУМЕ</Kicker><h2>{about.lead}</h2><div className="stats">{about.stats.map(s=><div key={s.label}><strong>{s.value}</strong><span>{s.label}</span></div>)}</div><div className="feature-list">{about.features.map((f,i)=><div key={f}><span>{String(i+1).padStart(2,'0')}</span><p>{f}</p></div>)}</div><div className="topic-marquee"><div>{[...about.topics,...about.topics].map((t,i)=><span key={i}>{t}</span>)}</div></div></div></section>}

function Venue(){const [photo,setPhoto]=useState(0);return <section className="scene venue" data-scene id="venue"><div className="venue-frame reveal"><img src={venue.images[photo]} alt="TAU — пространство музыкальных культур"/><div className="venue-overlay"><Kicker n="02">МЕСТО ПРОВЕДЕНИЯ</Kicker><h2>{venue.name}</h2><p>{venue.address}</p><Action href={venue.route} ghost>Смотреть на карте</Action></div><div className="venue-switch">{venue.images.map((src,i)=><button key={src} className={photo===i?'active':''} onClick={()=>setPhoto(i)}><span>0{i+1}</span><img src={src} alt=""/></button>)}</div></div></section>}

function Gallery(){return <section className="scene gallery" data-scene id="gallery"><div className="section-head reveal"><Kicker n="03">КАДРЫ С DEBT TECH 2025</Kicker><h2>Не рендер.<br/>Настоящее событие.</h2><a href={legacyContent.heroVideo.embedUrl} target="_blank" rel="noreferrer">Смотреть видео 2025 <Arrow/></a></div><DragRail className="gallery-rail">{gallerySources.map((src,i)=><figure key={src}><img src={src} alt={`DEBT TECH 2025 — кадр ${i+1}`} draggable="false"/><figcaption>FRAME / {String(i+1).padStart(2,'0')}</figcaption></figure>)}</DragRail><div className="rail-hint">DRAG / SCROLL</div></section>}

function Program(){const [active,setActive]=useState(0);return <section className="scene program" data-scene id="program"><div className="section-head reveal"><Kicker n="04">ЧТО ЖДЁТ УЧАСТНИКОВ</Kicker><h2>Три сцены.<br/><span>Один день в движении.</span></h2></div><div className="stage-system reveal"><div className="stage-media"><img src={stageImages[active]} alt=""/><span>0{active+1} / 03</span><h3>{stages[active].title}</h3><small>{stages[active].label}</small></div><div className="stage-index">{stages.map((s,i)=><button key={s.title} onClick={()=>setActive(i)} className={active===i?'active':''}><span>0{i+1}</span><b>{s.title}</b><small>{s.label}</small></button>)}</div></div><div className="program-grid reveal">{program.map((p,i)=><article key={p.id}><span>0{i+1}</span><h3>{p.title}</h3>{p.items.map(x=><p key={x}>{x}</p>)}</article>)}</div><div className="private-grid reveal">{privateZones.map((p,i)=><article key={p.title}><span>PRIVATE / 0{i+1}</span><h3>{p.title}</h3><p>{p.text}</p></article>)}</div></section>}

function Services(){const [active,setActive]=useState(0);return <section className="scene services" data-scene id="services"><div className="section-head reveal"><Kicker n="05">СЕРВИСЫ НА БОРТУ</Kicker><h2>Не витрина.<br/>Рабочие сценарии.</h2></div><div className="service-console reveal"><div className="service-tabs">{services.map((s,i)=><button key={s.title} className={active===i?'active':''} onClick={()=>setActive(i)}><span>0{i+1}</span><b>{s.title}</b><Arrow/></button>)}</div><article className="service-screen" key={active}><span>SERVICE / 0{active+1}</span><h3>{services[active].title}</h3><p className="service-lead">{services[active].lead}</p><div className="service-lines">{services[active].items.map(x=><p key={x}>{x}</p>)}</div><Action href="mailto:a.fefilova@rvzrus.ru">Связаться с менеджером</Action></article></div><ol className="service-steps reveal">{serviceSteps.map((x,i)=><li key={x}><span>0{i+1}</span><p>{x}</p></li>)}</ol></section>}

function Participants(){const [active,setActive]=useState(0);const angle=i=>`${(360/participants.length)*i}deg`;return <section className="scene participants" data-scene id="participants"><div className="section-head reveal"><Kicker n="06">УЧАСТНИКИ</Kicker><h2>12 групп рынка.<br/><span>Одна орбита встречи.</span></h2></div><div className="participants-layout reveal"><div className="orbit-ui"><div className="orbit-center"><small>DEBT TECH</small><strong>{String(active+1).padStart(2,'0')}</strong><span>{participants[active]}</span></div>{participants.map((p,i)=><button key={p} style={{'--a':angle(i)}} className={active===i?'active':''} onClick={()=>setActive(i)}><span>{String(i+1).padStart(2,'0')}</span></button>)}</div><div className="participant-list">{participants.map((p,i)=><button key={p} onClick={()=>setActive(i)} className={active===i?'active':''}><span>{String(i+1).padStart(2,'0')}</span><b>{p}</b></button>)}</div></div></section>}

function Organizer(){return <section className="scene organizer" data-scene id="organizer"><div className="organizer-layout reveal"><div className="organizer-copy"><Kicker n="07">ОРГАНИЗАТОР ФОРУМА</Kicker><img src="/assets/images/organizer/rvz-logo.svg" alt="Рынок Взыскания"/><h2>{organizer.lead}</h2><p>{organizer.license}</p><div className="organizer-stats">{organizer.stats.map(s=><div key={s.label}><strong>{s.value}</strong><span>{s.label}</span></div>)}</div></div><div className="organizer-cases"><article><img src="/assets/images/organizer/pko-300-2025.png" alt="Рейтинг ПКО-300"/><h3>{organizer.rating.title}</h3><p>{organizer.rating.text}</p></article><article><img src="/assets/images/organizer/navigator-preview.png" alt="DEBT TECH Навигатор"/><h3>{organizer.navigator.title}</h3><p>{organizer.navigator.text}</p></article></div></div><div className="organizer-features reveal">{organizer.features.map((f,i)=><p key={f}><span>0{i+1}</span>{f}</p>)}</div></section>}

function Conferences(){return <section className="scene conferences" data-scene id="conferences"><div className="section-head reveal"><Kicker n="08">ДРУГИЕ КОНФЕРЕНЦИИ СМИ «РЫНОК ВЗЫСКАНИЯ» 2021–2026</Kicker><h2>Архив событий.</h2></div><DragRail className="conference-rail">{conferences.map(c=><a href={c.href} target="_blank" rel="noreferrer" key={c.id}><img src={localConference[c.id]||c.image} alt="" draggable="false"/><div><b>{c.title}</b><strong>{c.year}</strong><Arrow/></div></a>)}</DragRail><div className="rail-hint">DRAG / SCROLL</div></section>}

function Tariffs({select}){return <section className="scene tariffs" data-scene id="tariffs"><div className="section-head reveal"><Kicker n="09">ТАРИФЫ</Kicker><h2>Выберите<br/>уровень доступа.</h2><p>Стоимость актуальна до 25 сентября.</p></div><div className="tariff-grid reveal">{tariffs.map((t,i)=><article key={t.id} className={i===1?'featured':''}><span>PASS / 0{i+1}</span><h3>{t.title}</h3><strong>{t.price}</strong><div>{tariffFeatures.map(f=><p key={f}>+ {f}</p>)}</div><Action onClick={()=>select(t)}>Принять участие</Action></article>)}</div></section>}

function Contacts(){return <section className="scene contacts" data-scene id="contacts"><div className="contacts-wrap reveal"><Kicker n="10">КОНТАКТЫ</Kicker><h2>{about.rendezvous}</h2><div className="contact-grid"><div><small>АККРЕДИТАЦИЯ СМИ</small><a href="mailto:org@rvzrus.ru">org@rvzrus.ru</a></div><div><small>БИЛЕТ УЧАСТНИКА</small><a href="mailto:a.fefilova@rvzrus.ru">a.fefilova@rvzrus.ru</a><a href="tel:+79657868846">+7 965 786 88 46</a></div><div><small>ПАРТНЕРСТВО И ВЫСТУПЛЕНИЯ</small><a href="mailto:org@rvzrus.ru">org@rvzrus.ru</a><a href="tel:+79252236707">+7 925 223 67 07</a></div></div><footer><span>© 2026 DEBT TECH</span><a href={links.privacy}>Политика конфиденциальности</a></footer></div></section>}

export default function App(){const [nav,setNav]=useState(false),[modal,setModal]=useState(null),[tariff,setTariff]=useState(null);useEffect(()=>{const io=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add('seen')),{threshold:.12,rootMargin:'0px 0px -8%'});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));return()=>io.disconnect()},[]);useEffect(()=>{document.body.style.overflow=(nav||modal)?'hidden':'';return()=>{document.body.style.overflow=''}},[nav,modal]);return <><SpaceStage/><ChapterNav open={nav} setOpen={setNav}/><main><Hero openRegistration={()=>setModal('registration')} openStand={()=>setModal('stand')}/><About/><Venue/><Gallery/><Program/><Services/><Participants/><Organizer/><Conferences/><Tariffs select={t=>{setTariff(t);setModal('registration')}}/><Contacts/></main>{modal&&<Modal kind={modal} tariff={tariff} close={()=>{setModal(null);setTariff(null)}}/>}</>}
