import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {FixedMenu} from './components/FixedMenu.jsx';
import {VideoDialog} from './components/VideoDialog.jsx';
import {ApplicationModal} from './components/ApplicationModal.jsx';
import {legacyContent} from './content/legacy.js';
import {event,ticker,about,venue,gallery,stages,program,privateZones,services,serviceSteps,participants,organizer,conferences,tariffFeatures,tariffs,links} from './content/site.js';
import BeyondHorizon from './vendor/BeyondHorizonOriginal.tsx';
import NeonBorder from './vendor/NeonBorderOriginal.tsx';
import GrainyCarousel from './vendor/GrainyCarouselReference.tsx';
import {LumenCta} from './vendor/LumenCta.tsx';
import {LiquidMetalButton} from './vendor/LiquidMetalButton.tsx';
import {CosmosField} from './components/CosmosField.jsx';
import {PredictiveArcCanvas} from './components/PredictiveArcCanvas.jsx';
import {ScrollHighlightV5} from './components/ScrollHighlightV5.jsx';
import {ScanButton} from './components/ScanButton.jsx';
import {assetUrl} from './lib/assets.js';
import './vendor/lumen-cta.css';
import './styles/cinema-v5.css';

const Arrow=()=> <svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 18 18 5M6 5h12v12" stroke="currentColor" strokeWidth="1.4"/></svg>;
const Label=({n,children})=><div className="v5-label"><span>{String(n).padStart(2,'0')}</span><b>{children}</b></div>;

function useSectionReveal(){useEffect(()=>{const els=[...document.querySelectorAll('[data-reveal]')];const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('is-visible')}),{threshold:.12,rootMargin:'0px 0px -8%'});els.forEach(el=>io.observe(el));return()=>io.disconnect()},[])}
function Tilt({children,className=''}){const move=e=>{if(matchMedia('(pointer:coarse)').matches)return;const r=e.currentTarget.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;e.currentTarget.style.setProperty('--rx',`${(-y*3).toFixed(2)}deg`);e.currentTarget.style.setProperty('--ry',`${(x*4).toFixed(2)}deg`);e.currentTarget.style.setProperty('--px',`${((x+.5)*100).toFixed(1)}%`);e.currentTarget.style.setProperty('--py',`${((y+.5)*100).toFixed(1)}%`)};const leave=e=>{e.currentTarget.style.setProperty('--rx','0deg');e.currentTarget.style.setProperty('--ry','0deg')};return <div className={`v5-tilt ${className}`} onPointerMove={move} onPointerLeave={leave}>{children}</div>}
function Countdown(){const [now,setNow]=useState(Date.now());useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);const left=Math.max(0,new Date(event.target)-now);const vals=[[Math.floor(left/864e5),'ДНЕЙ'],[Math.floor(left/36e5)%24,'ЧАСОВ'],[Math.floor(left/6e4)%60,'МИНУТ'],[Math.floor(left/1e3)%60,'СЕКУНД']];return <div className="v5-countdown"><small>ВРЕМЯ ДО ЗАПУСКА</small><div>{vals.map(([v,l])=><span key={l}><b>{String(v).padStart(2,'0')}</b><i>{l}</i></span>)}</div></div>}

function Hero({onRegister,onStand,onVideo}){const ref=useRef(null);const move=e=>{const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--hx',((e.clientX-r.left)/r.width-.5).toFixed(3));e.currentTarget.style.setProperty('--hy',((e.clientY-r.top)/r.height-.5).toFixed(3))};return <section id="top" className="v5-hero" ref={ref} onPointerMove={move}>
 <div className="v5-hero-horizon" aria-hidden="true"><BeyondHorizon background="#01040b" coreColor="#eef9ff" midColor="#2498ff" deepColor="#07245d" horizonY={.73} horizonRadius={1.5} coreSize={.008} coreHover={.036} haze={.055} brightness={.72} rimSpread={.045} speed={.15} fit={60} parallax={.45}/></div>
 <img className="v5-hero-planet" src={assetUrl('assets/cinema-v3/planet.png')} alt="" aria-hidden="true"/>
 <div className="v5-hero-orbit" aria-hidden="true"><i/><i/><i/></div>
 <div className="v5-hero-meta"><span>13 НОЯБРЯ 2026</span><span>МОСКВА · TAU</span></div>
 <div className="v5-hero-copy" data-reveal>
  <span className="v5-eyebrow">ЕЖЕГОДНАЯ ФОРУМ-ВЫСТАВКА</span>
  <h1><span>DEBT</span><span>TECH</span><em>2026</em></h1>
  <p>{event.headline}</p>
  <div className="v5-hero-actions"><div className="v5-lumen"><LumenCta label="Ранняя регистрация" hue={-26} brightness={1.08} onClick={onRegister}/></div><ScanButton variant="ghost" onClick={onStand}>Забронировать стенд</ScanButton></div>
 </div>
 <div className="v5-hero-control" data-reveal>
  <div className="v5-hero-control__video"><div className="v5-video-orb"><LiquidMetalButton variant="play" diameter={80} strokeWidth={2.1} rendering="colored" text="Видео 2025" embedded onClick={onVideo}/></div><div><span>КАК ЭТО БЫЛО</span><b>DEBT TECH 2025</b></div></div>
  <Countdown/>
 </div>
 <div className="v5-hero-ticker">{ticker.map((t,i)=><span key={i}>{t}</span>)}</div>
 </section>}

function About(){return <section id="about-forum" className="v5-section v5-about"><Label n={1}>О ФОРУМЕ</Label><div className="v5-about-grid"><div className="v5-about-manifesto" data-reveal><ScrollHighlightV5 text="DEBT TECH объединяет технологии, людей и практические решения для рынка долговых активов."/></div><Tilt className="v5-about-console"><div className="v5-glass v5-console-card"><span className="v5-console-glow"/><div className="v5-console-top"><small>DEBT TECH / 2026</small><span>ONLINE</span></div><h3>{about.lead}</h3><div className="v5-stats">{about.stats.map(s=><div key={s.label}><b>{s.value}</b><span>{s.label}</span></div>)}</div></div></Tilt></div><div className="v5-benefits" data-reveal>{about.features.map((f,i)=><article key={f}><span>0{i+1}</span><p>{f}</p></article>)}</div><div className="v5-topic-stream" aria-label="Темы форума">{about.topics.map((t,i)=><span key={`${t}-${i}`}>{t}</span>)}</div></section>}

function Venue(){const [active,setActive]=useState(0);return <section id="venue" className="v5-section v5-venue"><Label n={2}>МЕСТО ПРОВЕДЕНИЯ</Label><div className="v5-venue-frame" data-reveal><img src={venue.images[active]} alt={venue.name}/><div className="v5-venue-shade"/><div className="v5-venue-copy"><span>13 НОЯБРЯ 2026</span><h2>{venue.name}</h2><p>{venue.address}</p><ScanButton href={venue.route} variant="ghost">Смотреть на карте</ScanButton></div><div className="v5-venue-thumbs">{venue.images.map((src,i)=><button key={src} className={active===i?'is-active':''} onClick={()=>setActive(i)}><img src={src} alt=""/><span>0{i+1}</span></button>)}</div></div></section>}

function Gallery({onVideo}){const images=gallery.map(x=>x.src);return <section id="gallery" className="v5-section v5-gallery"><div className="v5-gallery-head"><Label n={3}>КАДРЫ С DEBT TECH 2025</Label><div><h2>Не рендер.<br/>Настоящее событие.</h2><button className="v5-video-link" onClick={onVideo}><span>Смотреть видео 2025</span><Arrow/></button></div></div><div className="v5-grain-wrap" data-reveal><GrainyCarousel images={images} background="#02050b" cardWidth={690} cardHeight={420} gap={20} rounded={4} speed={0} scroll={{mode:'snap',drag:22,damping:58,zoom:2.5}} grain={{speed:26,amount:7,scale:220}} style={{height:'520px'}}/></div><div className="v5-gallery-foot"><span>ПЕРЕТАЩИТЕ ЛЕНТУ</span><a href="https://rvz.bitrix24.ru/~0IZ9x" target="_blank" rel="noreferrer">Смотреть все фото <Arrow/></a></div></section>}

function Program(){const [active,setActive]=useState(0);return <section id="program" className="v5-section v5-program"><Label n={4}>ЧТО ЖДЁТ УЧАСТНИКОВ</Label><div className="v5-title-row"><h2>Три сцены.<br/><span>Три масштаба разговора.</span></h2><p>Деловая программа, продуктовые решения и отдельные форматы взаимодействия.</p></div><div className="v5-stage-deck" data-reveal>{stages.map((s,i)=><button key={s.title} className={`v5-stage ${active===i?'is-active':''}`} onClick={()=>setActive(i)} onPointerEnter={()=>setActive(i)} style={{'--stage-img':`url(${venue.images[i%venue.images.length]})`}}><div className="v5-stage-border">{active===i&&<NeonBorder color="#5cb8ff" rounded={30} thickness={1.2} borderSize={22} glow={28} speed={3.5} style={{position:'absolute',inset:0}}/>}</div><span>0{i+1}</span><div><small>{s.label}</small><h3>{s.title}</h3></div><Arrow/></button>)}</div><div className="v5-program-detail"><div className="v5-program-large"><span>АКТИВНАЯ СЦЕНА</span><h3>{stages[active].title}</h3><p>{stages[active].label}</p><div className="v5-program-line"/></div><div className="v5-program-cards">{program.map((p,i)=><article key={p.id}><span>0{i+1}</span><h4>{p.title}</h4>{p.items.map(x=><p key={x}>{x}</p>)}</article>)}</div></div><div className="v5-private-row">{privateZones.map((p,i)=><Tilt key={p.title} className="v5-private"><small>PRIVATE / 0{i+1}</small><h3>{p.title}</h3><p>{p.text}</p></Tilt>)}</div></section>}

function Services({onStand}){const [active,setActive]=useState(0);const s=services[active];return <section id="services" className="v5-section v5-services"><Label n={5}>СЕРВИСЫ НА БОРТУ</Label><div className="v5-services-shell" data-reveal><div className="v5-services-nav">{services.map((x,i)=><button key={x.title} onClick={()=>setActive(i)} className={active===i?'is-active':''}><span>0{i+1}</span><b>{x.title}</b><Arrow/></button>)}</div><div className="v5-service-stage"><PredictiveArcCanvas className="v5-service-arc" brightness={.72} speed={.22} spacing={8} dotSize={1.2} archHeight={.65}/><div className="v5-service-light"/><div className="v5-service-copy"><small>SERVICE / 0{active+1}</small><h2>{s.title}</h2><p>{s.lead}</p><ul>{s.items.map(x=><li key={x}>{x}</li>)}</ul>{active===1&&<ol>{serviceSteps.map(x=><li key={x}>{x}</li>)}</ol>}<ScanButton onClick={onStand}>Связаться с менеджером</ScanButton></div></div></div></section>}

function Participants(){const [active,setActive]=useState(0),[rotation,setRotation]=useState(0);const drag=useRef(null);const down=e=>{drag.current={x:e.clientX,r:rotation};e.currentTarget.setPointerCapture(e.pointerId)};const move=e=>{if(!drag.current)return;setRotation(drag.current.r+(e.clientX-drag.current.x)*.18)};const up=()=>drag.current=null;return <section id="participants" className="v5-section v5-participants"><Label n={6}>УЧАСТНИКИ</Label><div className="v5-participants-head"><h2>12 групп рынка.<br/><span>Одна точка встречи.</span></h2><p>Поверните поле или выберите категорию. Это карта состава аудитории, не география и не выдуманная сеть связей.</p></div><div className="v5-orbit-layout"><div className="v5-orbit" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} style={{'--rot':`${rotation}deg`}}><div className="v5-orbit-ring r1"/><div className="v5-orbit-ring r2"/><div className="v5-orbit-glow"/><div className="v5-orbit-core"><span>DEBT TECH</span><b>{String(active+1).padStart(2,'0')}</b><small>{participants[active]}</small></div>{participants.map((p,i)=>{const angle=i*30;const rad=i%2?205:150;return <button key={p} className={active===i?'is-active':''} style={{'--a':`${angle}deg`,'--r':`${rad}px`}} onClick={()=>setActive(i)} title={p}><span>{String(i+1).padStart(2,'0')}</span></button>})}</div><div className="v5-participant-list">{participants.map((p,i)=><button key={p} onClick={()=>setActive(i)} className={active===i?'is-active':''}><span>{String(i+1).padStart(2,'0')}</span>{p}</button>)}</div></div></section>}

function Organizer(){return <section id="organizer" className="v5-section v5-organizer"><Label n={7}>ОРГАНИЗАТОР ФОРУМА</Label><div className="v5-organizer-stage" data-reveal><div className="v5-organizer-light"/><div className="v5-organizer-copy"><span>{organizer.license}</span><h2>{organizer.title}</h2><p>{organizer.lead}</p><img src={assetUrl('assets/icons/organizers.svg')} alt="Организаторы"/></div><div className="v5-organizer-side"><div className="v5-organizer-stats">{organizer.stats.map(s=><div key={s.label}><b>{s.value}</b><span>{s.label}</span></div>)}</div><div className="v5-organizer-modules"><article><span>01</span><h3>{organizer.rating.title}</h3><p>{organizer.rating.text}</p></article><article><span>02</span><h3>{organizer.navigator.title}</h3><p>{organizer.navigator.text}</p></article></div></div></div></section>}

function Conferences(){const ref=useRef(null),state=useRef(null);const down=e=>{const el=ref.current;state.current={x:e.clientX,left:el.scrollLeft};el.setPointerCapture(e.pointerId)};const move=e=>{if(!state.current)return;ref.current.scrollLeft=state.current.left-(e.clientX-state.current.x)};const up=()=>state.current=null;return <section id="conferences" className="v5-section v5-conferences"><Label n={8}>ДРУГИЕ КОНФЕРЕНЦИИ СМИ «РЫНОК ВЗЫСКАНИЯ» 2021–2026</Label><div className="v5-title-row"><h2>Архив событий.</h2><p>От Петербургского форума взыскателей 2021 до DOLG TALK 2026.</p></div><div className="v5-conf-rail" ref={ref} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}>{conferences.map((c,i)=><a key={c.id} className="v5-conf-card" href={c.href} target="_blank" rel="noreferrer"><div className="v5-conf-media">{c.image?<img src={c.image} alt=""/>:<img src={gallery[(i*2)%gallery.length].src} alt=""/>}<span>{c.title}</span></div><div className="v5-conf-bottom"><b>{c.year}</b><Arrow/></div></a>)}</div><div className="v5-rail-hint">DRAG / SCROLL</div></section>}

function Tariffs({onSelect}){const [active,setActive]=useState(1);return <section id="tariffs" className="v5-section v5-tariffs"><Label n={9}>ТАРИФЫ</Label><div className="v5-title-row"><h2>Выберите уровень<br/><span>доступа.</span></h2><p>Стоимость актуальна до 25 сентября.</p></div><div className="v5-tariff-grid" data-reveal>{tariffs.map((t,i)=><Tilt key={t.id} className={`v5-tariff ${active===i?'is-active':''}`}><button className="v5-tariff-select" onClick={()=>setActive(i)} aria-label={`Выбрать ${t.title}`}/><span className="v5-tariff-index">PASS / 0{i+1}</span><h3>{t.title}</h3><strong>{t.price}</strong><div className="v5-tariff-features">{tariffFeatures.map(f=><span key={f}>+ {f}</span>)}</div><div className="v5-tariff-action"><ScanButton onClick={()=>onSelect(t)}>Принять участие</ScanButton></div>{active===i&&<div className="v5-tariff-neon"><NeonBorder color="#78c9ff" rounded={30} thickness={1} borderSize={18} glow={24} speed={4}/></div>}</Tilt>)}</div></section>}

function Contacts(){return <section id="contacts" className="v5-contacts"><div className="v5-contact-horizon" aria-hidden="true"><BeyondHorizon background="#02050b" coreColor="#ffffff" midColor="#2e9dff" deepColor="#061d52" horizonY={.83} horizonRadius={1.3} coreSize={.007} coreHover={.025} haze={.04} brightness={.62} rimSpread={.04} speed={.12} fit={56} parallax={.25}/></div><Label n={10}>КОНТАКТЫ</Label><h2>До встречи<br/><span>13 ноября в Москве.</span></h2><div className="v5-contact-grid"><article><small>АККРЕДИТАЦИЯ СМИ</small><a href="mailto:org@rvzrus.ru">org@rvzrus.ru</a></article><article><small>БИЛЕТ УЧАСТНИКА</small><a href="mailto:a.fefilova@rvzrus.ru">a.fefilova@rvzrus.ru</a><a href="tel:+79657868846">+7 965 786 88 46</a></article><article><small>ПАРТНЕРСТВО И ВЫСТУПЛЕНИЯ</small><a href="mailto:org@rvzrus.ru">org@rvzrus.ru</a><a href="tel:+79252236707">+7 925 223 67 07</a></article></div><footer><span>© 2026 DEBT TECH</span><a href={links.privacy}>Политика конфиденциальности</a></footer></section>}

export default function App(){useSectionReveal();const [form,setForm]=useState(null),[video,setVideo]=useState(false);const open=useCallback(v=>setForm(typeof v==='string'?{kind:v}:v),[]);const close=useCallback(()=>setForm(null),[]);const select=useCallback(t=>open({kind:'early-registration',tariff:t}),[open]);return <><CosmosField/><a className="skip-link" href="#main">К содержанию</a><div className="hero-only-view v5-shell"><FixedMenu site={legacyContent.site} menu={legacyContent.menu} video={legacyContent.heroVideo} onOpenApplication={open}/><main id="main" className="v5-main"><Hero onRegister={()=>open('early-registration')} onStand={()=>open('stand-booking')} onVideo={()=>setVideo(true)}/><About/><Venue/><Gallery onVideo={()=>setVideo(true)}/><Program/><Services onStand={()=>open('stand-booking')}/><Participants/><Organizer/><Conferences/><Tariffs onSelect={select}/><Contacts/></main></div>{video&&<VideoDialog video={legacyContent.heroVideo} onClose={()=>setVideo(false)}/>} {form&&<ApplicationModal key={`${form.kind}-${form.tariff?.id||''}`} kind={form.kind} selectedTariff={form.tariff} config={legacyContent.forms} privacyHref={links.privacy} onClose={close}/>}</>}
