name: Проверка сборки

on:
  push:
    branches:
      - fix/identichnaya-stranitsa
    paths:
      - '.github/workflows/check.yml'

permissions:
  contents: read

jobs:
  build:
    name: Проверка проекта
    runs-on: ubuntu-latest
    steps:
      - name: Получить файлы
        uses: actions/checkout@v4
      - name: Установить Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Установить зависимости
        run: npm ci
      - name: Собрать сайт
        run: npm run build
